name: setup-spark
description: 'Report fuzz test result'
inputs:
  native-engine:
    description: 'type of spark native engine (eg. blaze/comet/gluten)'
    required: true
runs:
  using: composite
  steps:
    - name: Generate title
      id: get-title
      shell: bash
      run: |
        today=$(date +'%Y-%m-%d')
        issue_title="[$today] Spark native engine fuzz test report of ${{ inputs.native-engine }}"
        echo "issue_title=$issue_title" >> $GITHUB_OUTPUT
    - name: report result of fuzz test
      if: ${{ hashFiles('results.md') != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
      run: |
        issue_title="${{ steps.get-title.outputs.issue_title }}"
        previous_issue_number=$(gh issue list --search "$issue_title in:title" --json number --jq '.[0].number')
        if [[ -n $previous_issue_number ]]; then
          # issue already exists, add comment
          gh issue comment $previous_issue_number --body-file results.md
        else
          # create new issue
          action_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          new_issue_url=$(gh issue create --title "$issue_title --body "Action: $action_url" --label ${{ inputs.native-engine }})
          gh issue comment $new_issue_url --body-file results.md
        fi
