name: setup-spark
description: 'Report fuzz test result'
inputs:
  native-engine:
    description: 'type of spark native engine (eg. blaze/comet/gluten)'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: composite
  steps:
    - name: Generate title
      id: get-title
      shell: bash
      run: |
        today=$(date +'%Y-%m-%d')
        issue_title="[$today][${{ inputs.native-engine }}] spark native engine fuzz test report"
        echo "issue_title=$issue_title" >> $GITHUB_OUTPUT
    - name: report result of fuzz test
      if: ${{ hashFiles('results.md') != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_REPO: ${{ github.repository }}
      run: |
        issue_title="${{ steps.get-title.outputs.issue_title }}"

        # truncate body if needed, Body is too long (maximum is 65536 characters) (addComment)
        # 262144(=65536 * 8 / 2)
        max_body_size=262144
        file_size=$(wc -c <results.md)
        if [ $file_size -ge $max_body_size ]; then
          truncate_msg="**Note**: The report is truncated due to issue comment length limit. You can download the complete report file in the action's artifacts."
          # add truncate message to the beginning of the file
          sed -i "1s/^/$truncate_msg\n/" results.md
          truncate --size $max_body_size results.md
        fi

        previous_issue_number=$(gh issue list --search "$issue_title in:title" --json number --jq '.[0].number')
        if [[ -n $previous_issue_number ]]; then
          # issue already exists, add comment
          gh issue comment $previous_issue_number --body-file results.md
        else
          # create new issue
          action_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          new_issue_url=$(gh issue create --title "$issue_title" --body "Action: $action_url" --label ${{ inputs.native-engine }})
          gh issue comment $new_issue_url --body-file results.md
        fi
    - name: Upload result
      if: ${{ hashFiles('results.md') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: fuzz-test-result-${{ inputs.native-engine }}-${{ github.run_id }}
        path: results.md
        overwrite: true
